### ISSUE TITLE
Prevent standard select box from showing/loading on page load/refresh

### ISSUE THREAD

**Issue by Adyyda** [lcdsantos/jQuery-Selectric#102]
Hello. When the page loads (or is refreshed), for a fraction of a second (more on a slower connection), we can see the standard select box and than we see the proper selectric. Can it be changed so that we do not see the standard select box? I have managed to capture it with print screen

![untitled](https://cloud.githubusercontent.com/assets/5921012/10950948/37ef2e5c-8343-11e5-947f-754b996c992d.png)

**Comment by lcdsantos** [comment]
You could do something like this, in your css:

```css
select {
  visibility: hidden;
}

.selectric-hide-select select {
  visibility: visible;
}
```
