### ISSUE TITLE
Scrolling up the list doesn't work

### ISSUE THREAD

**Issue by henriquea** [lcdsantos/jQuery-Selectric#52]
I have this case where I couldn't scroll up the list, set the `height` and `overflow` to `.selectricScroll` solved my problem.

```css
.selectricScroll {
  height: 300px;
  overflow: scroll;
}
```
