### ISSUE TITLE
Expand only downwards.

### ISSUE THREAD

**Issue by Vishnja** [lcdsantos/jQuery-Selectric#57]
Hello! How dropdown can be cofigured to expand only downwards.
P.S. I don't know whether it's proper place to post this question.

**Comment by lcdsantos** [comment]
Remove this rule from your CSS:
```css
.selectricAbove .selectricItems {
  top: auto;
  bottom: 100%;
}
```
